version: '3.7'

services:
  frontend:    
    image:  
      "marcoprado20/scorpion-front"
    ports:
      - 3030:80
  backend:
    image: 
      "marcoprado20/scorpion-training"
    ports:
      - 8000:8000
  backend2:
    image: 
      "marcoprado20/scorpion-prediction"
    ports:
      - 9000:9000